apiVersion: entando.org/v1
kind: EntandoDeBundle
metadata:
  name: example-bundle
  namespace: ciccio
  labels:
    widget: 'true'
spec:
  details:
    name: example-bundle
    description: This is an example of an Entando 6 bundle
    dist-tags:
      latest: v0.0.1
    versions:
      - v0.0.1
  tags:
    - version: v0.0.1
      shasum: 27c6442aa50f6bc6a7ae59d0c6f0eda6b57998d6
      integrity: 27c6442aa50f6bc6a7ae59d0c6f0eda6b57998d6
      tarball: 'git@github.com:pietrangelo/entando-bundle.git'

